Repository simra-project/SimRa-Visualization, pull requests merged in 2020-01, with the labels that each got.

#85 File and Folder change Observer updated.
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/controller/MonitorService.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/RecursiveWatcherService.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/RideParserThreaded.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/SimraFileAlterationListenerAdaptor.java
Labels: enhancement

#101 * incident description for linebreak and comma fixed.
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/model/IncidentEntity.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/IncidentParserThreaded.java
Labels: bug

#100 * matched location and incident location field index auto setup.
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/CsvimporterApplication.java
Labels: enhancement

#103 Feature/incident route highlight
  frontend/public/ApiWorker.js
  frontend/src/components/MapPopup.vue
  frontend/src/services/ApiService.ts
  frontend/src/services/IncidentUtils.ts
  frontend/src/views/Map.vue
Labels: Merge conflict

#117 Filterbare properties clean
  README.md
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/model/RideEntity.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/RecursiveWatcherService.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/RideParserThreaded.java
  backend/csvimporter/src/main/java/com/simra/app/csvimporter/service/SimraFileAlterationListenerAdaptor.java
Labels: Approved / Waiting for merge
